[package]
name = "bevy_event_entities"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_reflect = "0.13.2"
bevy_app = "0.13.2"
bevy_utils = "0.13.2"
bevy_log = "0.13.2"
bevy_ecs = "0.13.2"
bevy_hierarchy = "0.13.2"

[dev-dependencies]
bevy = "0.13.2"
rand = "0.8.5"
